name: nows_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.10.0+4
  path_provider: ^2.0.11
  path: ^1.8.2
  flutter_spinkit: ^5.1.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.3
  email_validator: '^2.1.16'
  firebase_storage: ^11.0.9
  firebase_database: ^10.0.8
  random_string_generator: ^2.0.0
  image_picker: ^0.8.6
  flutter_map: ^3.0.0
  flutter_map_location_marker: ^5.0.0+1
  latlong2: ^0.8.1
  geolocator: ^9.0.2
  url_launcher: ^6.1.7
  envied: ^0.3.0
  build_runner: ^2.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  envied_generator: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/gps-icon.png
    - assets/icons/post-icon.png
    - assets/images/placeholder_image.png
    - assets/images/mapbox-logo-black.png
    - assets/images/mapbox-logo-white.png
    - assets/images/flutter-map-logo-black.png
    - assets/images/flutter-map-logo-white.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app-icon.png"
  min_sdk_android: 21